'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Namespace WebMVC

    Partial Public Class GrahamEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=GrahamEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Notas() As DbSet(Of Nota)
        Public Overridable Property P_Alumno() As DbSet(Of P_Alumno)
        Public Overridable Property P_Materia() As DbSet(Of P_Materia)
        Public Overridable Property View_MateriaActiva() As DbSet(Of View_MateriaActiva)
        Public Overridable Property View_ListaAlumnos() As DbSet(Of View_ListaAlumnos)
        Public Overridable Property View_ListaPromedio() As DbSet(Of View_ListaPromedio)
    
        Public Overridable Function PA_Alumno_Consultar() As ObjectResult(Of PA_Alumno_Consultar_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PA_Alumno_Consultar_Result)("PA_Alumno_Consultar")
        End Function
    
        Public Overridable Function PA_MateriasActivas_Consultar() As ObjectResult(Of PA_MateriasActivas_Consultar_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PA_MateriasActivas_Consultar_Result)("PA_MateriasActivas_Consultar")
        End Function
    
    End Class

End Namespace
