'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebMVC

    Partial Public Class Nota
        Public Property IdNota As Integer
        Public Property IdMateria As Integer
        Public Property Nota1 As Decimal
        Public Property FechaNota As Date
    
        Public Overridable Property P_Materia As P_Materia
    
    End Class

End Namespace
