'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebMVC

    Partial Public Class P_Materia
        Public Property IdMateria As Integer
        Public Property Nombre As String
    
        Public Overridable Property Notas As ICollection(Of Nota) = New HashSet(Of Nota)
    
    End Class

End Namespace
