'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebMVC

    Partial Public Class View_MateriaActiva
        Public Property Identificacion As String
        Public Property Alumno As String
        Public Property Carrera As String
        Public Property IdMateria As Integer
        Public Property Materia As String
    
    End Class

End Namespace
